name: Automated API tests using Postman CLI

on: 
  push:
    branches:
      - main

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: |
          part1="PMAK-66741d42074366000122"
          part2="b1ed-69542ade8bed106d736758f4f62f6b82b4"
          postman login --with-api-key "$part1$part2"
      - name: Run API tests
        run: |
          postman collection run "36312693-dfb8150e-5a9e-4ff2-97ee-a0695f71641f" -e "36312693-8525c593-69d9-4dad-81b0-0386cb7d2156"
